name: 23/01/Trebuchet

on:
  push:
    paths:
      - '23/01/Trebuchet/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      build_path:
        description: 'Path to build'
        required: true
        default: '23/01/Trebuchet'

jobs:
  run:
    uses: ./.github/workflows/zig_run_template.yml
    with:
      build_path: ${{ github.event.inputs.build_path }}
