name: 23/01/Trebuchet

on:
  push:
    paths:
      - '23/01/Trebuchet/**'
      - '.github/**'
  workflow_dispatch:

env:
  # Set challenge path
  CHALLENGE_PATH: '23/01/Trebuchet'

jobs:
  run:
    uses: ./.github/workflows/zig_run_template.yml
    with:
      build_path: $CHALLENGE_PATH
