name: 23/01/Trebuchet

on:
  push:
    paths:
      - '23/01/Trebuchet/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/zig_run_template.yml
    with:
      build_path: '23/01/Trebuchet'
