name: 23/01/Trebuchet

on:
  push:
    paths:
      - '23/01/Trebuchet/**'
  workflow_dispatch:
    inputs:
      build_path:
        description: 'Path to test files'
        required: true
        default: '23/01/Trebuchet/build.zig'

jobs:
  test:
    uses: ./.github/workflows/zig_test_template.yml
    with:
      test_path: ${{ github.event.inputs.build_path }}

  build:
    uses: ./.github/workflows/zig_build_template.yml
    with:
      build_path: ${{ github.event.inputs.build_path }}
