name: Zig Build Template

on:
  push:
    branches:
      - main
    paths:
      - '**/*.zig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Build
        run: zig build -Drelease-safe --path ${{ github.workspace }}/${{ github.event.inputs.build_path }}
