name: Zig Build Template

on:
  workflow_call:
      
jobs:
  reusable-zig-run:
    name: Build on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Verify build path
        run: echo "Build path $CHALLENGE_PATH exists"

      - name: Test
        working-directory: $CHALLENGE_PATH
        run: zig build test

      - name: Build
        working-directory: $CHALLENGE_PATH
        run: zig build run

      # Optionally, add steps to handle the build artifacts (like archiving them)
