name: Zig Release Template

on:
  workflow_call:
    inputs:
      release_path:
        description: 'Path for release (containing build.zig)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Change to Release Directory
        run: cd ${{ inputs.release_path }}

      - name: Build for Release
        run: zig build -Drelease-safe

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'release-${{ github.run_number }}'
          release_name: 'Release for ${{ github.event.repository.name }} - ${{ github.run_number }}'
          draft: false
          prerelease: false

      # Add steps to upload any build artifacts or binaries as part of the release
