name: Zig Test Template

on:
  workflow_call:
    inputs:
      test_path:
        description: 'Path to test files'
        required: true
        type: string

jobs:
  test:
    name: Test on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Change to Build directory
        run: cd ${{ input.build_path }}
 
      - name: Run Tests
        run: zig build test --summary all
