name: Zig Test Template

on:
  push:
    branches:
      - '!main'
    paths:
      - '**.zig'
  pull_request:
    branches:
      - '!main'
    paths:
      - '**.zig'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Zig Tests
        run: zig test your_test_file.zig
