name: Zig Build Template

on:
  workflow_call:
    inputs:
      build_path:
        description: 'Path to the build directory'
        required: true
        type: string
      
jobs:
  run:
    name: Build on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Pwd
        working-directory: ${{ inputs.build_path }}
        run: pwd

      - name: Test
        working-directory: ${{ inputs.build_path }}
        run: zig build test

      - name: Build
        working-directory: ${{ inputs.build_path }}
        run: zig build run

      # Optionally, add steps to handle the build artifacts (like archiving them)
