name: Zig Test Template

on:
  push:
    paths:
      - '**/*.zig'
    branches:
      - main

jobs:
  test:
    name: Test on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Run Tests
        run: zig test ${{ github.workspace }}/${{ github.event.inputs.test_path }}
